name: Check website

on:
  pull_request:
    branches:
      - main

jobs:
  seeneva_web_check:
    name: Check Seeneva website
    runs-on: ubuntu-latest
    steps:
      - name: Download Zola binary
        run: wget -qO- https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar -xvz -C ${HOME}
        env:
          ZOLA_VERSION: 0.13.0

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install npm packages
        run: npm install

      - name: Run Zola check
        run: ${HOME}/zola check
