name: Deploy website

on:
  push:
    branches:
      - main

jobs:
  seeneva_web_deploy:
    name: Deploy Seeneva website
    runs-on: ubuntu-latest
    steps:
      - name: Download Zola binary
        run: wget -qO- https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar -xvz -C ${HOME}
        env:
          ZOLA_VERSION: 0.13.0

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install npm packages
        run: npm install

      - name: Run Zola build
        run: ${HOME}/zola build

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          target_branch: gh-pages
          build_dir: public
          commit_message: Deploy seeneva.app to GitHub pages
          fqdn: seeneva.app
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
